#!/usr/bin/env bash
sudo echo "sudo works"

# directory of this script
DIR="$( cd "$( dirname "$0" )" && pwd )"
source $DIR/bash_profile
cd `~`

bold=$(tput bold)
normal=$(tput sgr0)

green=$(tput setaf 2)
yellow=$(tput setaf 3)
red=$(tput setaf 1)

state=( green yellow red )

function message {
  color=${!state[$1]}
  printf '%30s\t%s\n' "${bold}${color}$file" "${normal}$2" 
}

for file in $DIR/*
do
  file=$(basename $file)
  target="$HOME/.${file}"

  # ignore this file and .git dir

  [ $file = `basename $0` ] && continue
  [ $file = '.git' ] && continue

  # target exists for reals
  [ -f "$target" ] && [ ! -L "$target" ] && message 2 "file exists and is not a symlink" && continue

  # $target already linked
  if [ -L "$target" ]
  then
    existing=`ls -l $target | awk '{print $11}'`
    if [ $existing = $file ]
    then
      # to this dir
      message 0 "set correctly"
      continue
    else
      # to a different dir
      message 1 "already linked to $existing"
      continue
    fi
  fi

  # symlink created
  ln -s $DIR/$file ".$file"
  message 0 "file linked"
done

# Hub
cd $DIR/lib/hub
rvm --create 1.9.3@hub
rvm 1.9.3@hub do bundle install
rvm 1.9.3@hub do rake install prefix=$DIR/lib
cd ~

# DotJS
cd $DIR/lib/dotjs-ubuntu
rvm --create 1.9.3@dotjs
rvm 1.9.3@dotjs do rake install && google-chrome --install-from-webstore dlnccnmhpmdidoiecanghgienhoglnim
cd ~

# Other Gems
rvm default do gem install serve gist

# Crontab
crontab -u will ~/.lib/crontab

# Vundle
if [ ! "~/.vim/bundle/vundle" ]; then
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi
vim +BundleInstall +qa

# Rainbarf (tmux status line)
sudo apt-get install cpanminus
cpanm git://github.com/creaktive/rainbarf.git
sudo cpan -i App::rainbarf

# Keyboard
sudo cp $DIR/lib/keyboard /etc/default/keyboard


